Update packging framework

diff --git a/debprep b/debprep
--- a/debprep
+++ b/debprep
@@ -1,53 +1,50 @@
 #!/bin/sh
 
-logmsg() { echo $1 >&2; }
-
-pkgname=${1:-${PKGNAME}}
-workdir=${2:-${pkgname}}
-if [ "${workdir}" = "-" ] || [ "${workdir}" = "." ]; then
-    workdir=${pkgname};
+if [ -f packaging.sh ]; then
+    . packaging.sh
+else
+    script_root=$(dirname $0);
+    if [ -f ${script_root}/packaging.sh ]; then
+	. ${script_root}/packaging.sh;
+    else
+	echo "Can't find packaging.sh init";
+	exit 2;
+    fi;
 fi;
 
-version=$(cat state/VERSION)
-rel_version=$(cat state/REL_VERSION)
-branch=$(cat state/BRANCH);
-channel=$(cat state/CHANNEL);
-full_version=$(cat state/FULL_VERSION || echo $version);
-major_version=$(cat state/MAJOR_VERSION || echo $version);
-minor_version=$(cat state/MINOR_VERSION || echo $version);
-base_version=$(cat state/BASE_VERSION || echo $version);
-distro=$(cat state/DISTRO || lsb_release -s -c || echo debian)
-status=$(cat state/STATUS || echo stable)
-urgency=$(cat state/URGENCY || echo normal)
-
+workdir=${2:-${PKGNAME}}
 if [ -d ${workdir} ]; then logmsg "Removing current ${workdir}"; rm -rf ${workdir}; fi
-logmsg "Unpacking ${pkgname}.tar into ${workdir}";
-mkdir ${workdir}; ("cd" ${workdir}; tar xf ../${pkgname}.tar);
-if [ -d ${workdir}/debian ]; then rm -rf ${workdir}/debian; fi
-if [ ! -f state/NOSOURCE ]; then
-    logmsg "Creating source tarball at ${pkgname}_${rel_version}.orig.tar.gz";
-    tar -czf ${pkgname}_${rel_version}.orig.tar.gz ${workdir};
-fi;
-mkdir ${workdir}/debian
 logmsg "Creating build directory at '${workdir}'"
-("cd" debinfo/${pkgname};
+mkdir ${workdir}; ("cd" ${workdir}; tar xf ../${PKGNAME}.tar);
+if [ ! -f state/NOSOURCE ]; then
+    srctar=${PKGNAME}_${REL_VERSION}.orig.tar.gz;
+    logmsg "Creating source tarball at ${srctar}";
+    tar -czf ${srctar} ${workdir};
+fi;
+if [ -d ${workdir}/debian ]; then rm -rf ${workdir}/debian; fi
+mkdir ${workdir}/debian
+logmsg "Setting up ${workir}/debian";
+("cd" debinfo/${PKGNAME};
  for file in *; do
      if [ -d ${file} ]; then
 	 cp -r ${file} ../../${workdir}/debian;
      else
 	 u8_xsubst ${file} ../../${workdir}/debian/${file} \
-		   "VERSION" "${rel_version}" \
-		   "BASE_VERSION" "${base_version}" \
-		   "FULL_VERSION" "${full_version}" \
-		   "MINOR_VERSION" "${minor_version}" \
-		   "MAJOR_VERSION" "${major_version}";
+		   "VERSION" "${REL_VERSION}"              \
+		   "CHANNEL" "${CHANNEL}"                  \
+		   "BRANCH" "${BRANCH}"                    \
+		   "DISTRO" "${DISTRO}"                    \
+		   "BASE_VERSION" "${BASE_VERSION}"        \
+		   "FULL_VERSION" "${FULL_VERSION}"        \
+		   "MINOR_VERSION" "${MINOR_VERSION}"      \
+		   "MAJOR_VERSION" "${MAJOR_VERSION}";
      fi;
  done);
-cp -r debinfo/${pkgname} ${workdir}/debian
-for x in BRANCH VERSION FULL_VERSION BASE_VERSION; do cp state/$x ${pkgname}; done
-
-./deb_changelog ${pkgname} "${DISTRO}" "${rel_version}" "${channel}" \
-		"${STATUS}" "${URGENCY}" "${full_version}" \
+for custom in ${workdir}/debian/*.${DISTRO}; do
+    if [ -f ${custom} ]; then
+	mv ${custom} ${workdir}/debian/$(basename ${custom});
+    fi;
+done;
+./deb_changelog ${pkgname} "${DISTRO}" "${REL_VERSION}" "${CHANNEL}" \
+		"${STATUS}" "${URGENCY}" "${FULL_VERSION}" \
 	 1> ${workdir}/debian/changelog;
-cat debinfo/${pkgname}/changelog >> ${workdir}/debian/changelog;
-
