Make package manager calls use -yq

diff --git a/tools/debtool b/tools/debtool
--- a/tools/debtool
+++ b/tools/debtool
@@ -247,7 +247,7 @@ case ${ACTION} in
 		debinstall $* && echo ${FULL_VERSION} > run/INSTALLED.${PKGNAME};
 	    fi;
 	fi;
-	(${SUDO} apt upgrade ${PKGNAME}) || (echo "Upgrade of ${PKGNAME} failed");
+	(${SUDO} apt-get -yq install ${PKGNAME}) || (echo "Upgrade of ${PKGNAME} failed");
 	APTVERSION=$(u8_aptversion ${PKGNAME});
 	if [ "${APTVERSION}" != "${VERSION}" ]; then
 	    ./setsource ${PKGNAME} && 
diff --git a/tools/rpmtool b/tools/rpmtool
--- a/tools/rpmtool
+++ b/tools/rpmtool
@@ -180,7 +180,7 @@ case ${ACTION} in
 		rpminstall $* && echo ${XVERSION} > work/${PKGNAME}/INSTALLED;
 	    fi;
 	fi;
-	(${SUDO} dnf upgrade ${PKGNAME}) || (echo "Upgrade of ${PKGNAME} failed");
+	(${SUDO} dnf -yq upgrade ${PKGNAME}) || (echo "Upgrade of ${PKGNAME} failed");
 	YUMVERSION=$(yum_version ${PKGNAME});
 	# Check whether we need to build the package, then do it
 	if [ "${YUMVERSION}" != "${VERSION}" ]; then
